### ISSUE TITLE
Can't instantiate, Incompatible API version

### ISSUE THREAD

**Issue by twmcelroy** [fortinet/terraform-provider-fortios#4]
I am running Terraform v0.12.1. I downloaded and made the fortios plugin. When I run terraform init or terraform init -upgrade, no errors. When I run terraform plan:
Error: Failed to instantiate provider "fortios" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

Is the fortios provider compatible with Terraform v0.12.x?

**Comment by frankshen01** [comment]
Hi @twmcelroy , thanks for reporting this issue. We currently do not support terraform v0.12, we are working on it, terraform v0.12 will be supported soon.  

BTW, since the Terraform code has been released from terraform-providers repository, and the issue was submitted at terraform-providers repository: https://github.com/terraform-providers/terraform-provider-fortios/issues/7 , can we close the issue here and track them under https://github.com/terraform-providers/terraform-provider-fortios/issues instead?

**Comment by twmcelroy** [comment]
Yes that makes sense to track it there. I’ll look for it and follow it there. 
    	
    	

    	Travis
    
  




On Sat, Jun 15, 2019 at 9:07 PM -0500, "frankshen01" <notifications@github.com> wrote:












Hi @twmcelroy , thanks for reporting this issue. We currently do not support terraform v0.12, we are working on it, terraform v0.12 will be supported soon.


BTW, since the Terraform code has been released from terraform-providers repository, and the issue was submitted at terraform-providers repository: terraform-providers/terraform-provider-fortios#7 , can we close the issue here and track them under https://github.com/terraform-providers/terraform-provider-fortios/issues instead?

**Comment by frankshen01** [comment]
Terraform FortiOS provider v1.1.0 has supported Terraform v0.12.2 now, please refer to: https://github.com/terraform-providers/terraform-provider-fortios/releases/tag/v1.1.0 

Hi Admin, could you please help to close the issue?
